name: 'data_foundation_conformed'
version: '1.0.0'
config-version: 2
profile: 'default'
model-paths: ['models']
analysis-paths: ['analysis']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']
target-path: 'dbt_packages'
clean-targets:
  - 'dbt_packages'
  - 'target'
require-dbt-version: ['&gt;=1.5.0']
models:
  data_foundation_conformed:
    reference:
      +schema: reference
timestamp-strategy: sha256